/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author USER
 */
public class PilihGambarDenganCombobox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarDenganCombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CbPilih = new javax.swing.JComboBox<>();
        ImagePanel = new javax.swing.JPanel();
        ImgGold = new javax.swing.JLabel();
        ImgBesar = new javax.swing.JLabel();
        ImgNpc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPanel.setBackground(new java.awt.Color(255, 102, 255));

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BtnPanel.add(jButton1);

        CbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold Fish", "Mata Besar", "Npc" }));
        CbPilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbPilihItemStateChanged(evt);
            }
        });
        CbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPilihActionPerformed(evt);
            }
        });
        BtnPanel.add(CbPilih);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setBackground(new java.awt.Color(51, 51, 255));
        ImagePanel.setLayout(new java.awt.CardLayout());

        ImgGold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgGold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/gold fish.jpg"))); // NOI18N
        ImagePanel.add(ImgGold, "0");

        ImgBesar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgBesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ikan mata besar.jpg"))); // NOI18N
        ImagePanel.add(ImgBesar, "1");

        ImgNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgNpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/npc spongebob.jpg"))); // NOI18N
        ImagePanel.add(ImgNpc, "2");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbPilihActionPerformed

    private void CbPilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbPilihItemStateChanged
        CardLayout cl = (CardLayout) (ImagePanel.getLayout());
        cl.show(ImagePanel, String.valueOf(CbPilih.getSelectedIndex()));
    }//GEN-LAST:event_CbPilihItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarDenganCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarDenganCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarDenganCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarDenganCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarDenganCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JComboBox<String> CbPilih;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImgBesar;
    private javax.swing.JLabel ImgGold;
    private javax.swing.JLabel ImgNpc;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
