/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author USER
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        BtGold = new javax.swing.JButton();
        BtBesar = new javax.swing.JButton();
        BtNpc = new javax.swing.JButton();
        BtKeluar = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        ImgGold = new javax.swing.JLabel();
        ImgNpc = new javax.swing.JLabel();
        ImgBesar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPanel.setBackground(new java.awt.Color(102, 102, 102));

        BtGold.setText("Gold Fish");
        BtGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGoldActionPerformed(evt);
            }
        });
        BtnPanel.add(BtGold);

        BtBesar.setText("Mata Besar");
        BtBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBesarActionPerformed(evt);
            }
        });
        BtnPanel.add(BtBesar);

        BtNpc.setText("Npc");
        BtNpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNpcActionPerformed(evt);
            }
        });
        BtnPanel.add(BtNpc);

        BtKeluar.setText("Keluar");
        BtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKeluarActionPerformed(evt);
            }
        });
        BtnPanel.add(BtKeluar);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setBackground(new java.awt.Color(51, 255, 255));
        ImagePanel.setLayout(new java.awt.CardLayout());

        ImgGold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgGold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/gold fish.jpg"))); // NOI18N
        ImagePanel.add(ImgGold, "0");

        ImgNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgNpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/npc spongebob.jpg"))); // NOI18N
        ImagePanel.add(ImgNpc, "2");

        ImgBesar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgBesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ikan mata besar.jpg"))); // NOI18N
        ImagePanel.add(ImgBesar, "1");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGoldActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "0");
    }//GEN-LAST:event_BtGoldActionPerformed

    private void BtBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBesarActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "1");
    }//GEN-LAST:event_BtBesarActionPerformed

    private void BtNpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNpcActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "2");
    }//GEN-LAST:event_BtNpcActionPerformed

    private void BtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBesar;
    private javax.swing.JButton BtGold;
    private javax.swing.JButton BtKeluar;
    private javax.swing.JButton BtNpc;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImgBesar;
    private javax.swing.JLabel ImgGold;
    private javax.swing.JLabel ImgNpc;
    // End of variables declaration//GEN-END:variables
}
